# Generated by Django 5.2 on 2025-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.CharField(blank=True, max_length=255, null=True)),
                ('strategic_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('aim', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('main_activity', models.TextField(blank=True, null=True)),
                ('Beneficial_Society', models.TextField(blank=True, null=True)),
                ('Beneficial_Body', models.TextField(blank=True, null=True)),
                ('Budget_Government', models.FloatField(blank=True, null=True)),
                ('Budget_Society', models.FloatField(blank=True, null=True)),
                ('Other_Budget', models.FloatField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
