# Generated by Django 5.2 on 2025-04-27 13:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_activity_rename_budget_government_directorplan_april_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='strategic_goal',
            new_name='astrategic_goal',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Beneficial_Body',
            new_name='beneficial_body',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Beneficial_Society',
            new_name='beneficial_society',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Budget_Government',
            new_name='budget_government',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Budget_Society',
            new_name='budget_society',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='agencyplan',
            old_name='Other_Budget',
            new_name='other_budget',
        ),
        migrations.RenameField(
            model_name='directorplan',
            old_name='auguest',
            new_name='august',
        ),
        migrations.AddField(
            model_name='directorplan',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorplan',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agency', 'Agency'), ('director', 'Director')], default='admin', max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('groups', models.ManyToManyField(blank=True, related_name='userprofile_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='userprofile_set', to='auth.permission')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='agencyplan',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_plans', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='directorplan',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_plans', to='core.userprofile'),
        ),
    ]
